version: '3.7'

services:
    grafana:
        image: grafana/grafana:7.0.0
        volumes:
            - ./:/var/lib/grafana/plugins/special-map-panel
        environment: 
            - GF_INSTALL_PLUGINS=simpod-json-datasource
        ports: 
            - 3000:3000